#pragma once

// List each complete storage unit in the original PowerPC MSB-first order:
//   AURORA_PPC_BITFIELD_GROUP(unsigned, (active, 1), (mode, 2), (, 29))
// The host declarations preserve original numeric masks, including multi-bit
// field values. Named fields and raw word aliases therefore share one layout.
// This describes native CPU words, not the byte order of serialized resources.
// Each group accepts 1-32 (name, width) pairs and must fill its storage type.
// An empty name declares padding. Adjacent storage units use separate groups.

#define AURORA_DETAIL_PPC_JOIN_I(a, b) a##b
#define AURORA_DETAIL_PPC_JOIN(a, b) AURORA_DETAIL_PPC_JOIN_I(a, b)
#define AURORA_DETAIL_PPC_UNPAREN(...) __VA_ARGS__
#define AURORA_DETAIL_PPC_FIELD_I(type, name, width) type name : width;
#define AURORA_DETAIL_PPC_FIELD_EXPAND(...) AURORA_DETAIL_PPC_FIELD_I(__VA_ARGS__)
#define AURORA_DETAIL_PPC_FIELD(type, field) \
  AURORA_DETAIL_PPC_FIELD_EXPAND(type, AURORA_DETAIL_PPC_UNPAREN field)
#define AURORA_DETAIL_PPC_WIDTH_I(name, width) width
#define AURORA_DETAIL_PPC_WIDTH(field) AURORA_DETAIL_PPC_WIDTH_I field
#define AURORA_DETAIL_PPC_COUNT_I(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, count, ...) count
#define AURORA_DETAIL_PPC_COUNT(...) AURORA_DETAIL_PPC_COUNT_I(__VA_ARGS__, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)

#define AURORA_DETAIL_PPC_FORWARD_1(type, field) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_REVERSE_1(type, field) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_1(field) AURORA_DETAIL_PPC_WIDTH(field)
#define AURORA_DETAIL_PPC_VALID_1(type, field) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8)
#define AURORA_DETAIL_PPC_FORWARD_2(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_1(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_2(type, field, ...) AURORA_DETAIL_PPC_REVERSE_1(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_2(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_1(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_2(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_1(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_3(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_2(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_3(type, field, ...) AURORA_DETAIL_PPC_REVERSE_2(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_3(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_2(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_3(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_2(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_4(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_3(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_4(type, field, ...) AURORA_DETAIL_PPC_REVERSE_3(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_4(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_3(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_4(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_3(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_5(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_4(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_5(type, field, ...) AURORA_DETAIL_PPC_REVERSE_4(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_5(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_4(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_5(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_4(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_6(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_5(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_6(type, field, ...) AURORA_DETAIL_PPC_REVERSE_5(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_6(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_5(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_6(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_5(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_7(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_6(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_7(type, field, ...) AURORA_DETAIL_PPC_REVERSE_6(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_7(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_6(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_7(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_6(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_8(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_7(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_8(type, field, ...) AURORA_DETAIL_PPC_REVERSE_7(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_8(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_7(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_8(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_7(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_9(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_8(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_9(type, field, ...) AURORA_DETAIL_PPC_REVERSE_8(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_9(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_8(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_9(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_8(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_10(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_9(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_10(type, field, ...) AURORA_DETAIL_PPC_REVERSE_9(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_10(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_9(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_10(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_9(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_11(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_10(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_11(type, field, ...) AURORA_DETAIL_PPC_REVERSE_10(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_11(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_10(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_11(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_10(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_12(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_11(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_12(type, field, ...) AURORA_DETAIL_PPC_REVERSE_11(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_12(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_11(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_12(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_11(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_13(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_12(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_13(type, field, ...) AURORA_DETAIL_PPC_REVERSE_12(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_13(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_12(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_13(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_12(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_14(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_13(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_14(type, field, ...) AURORA_DETAIL_PPC_REVERSE_13(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_14(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_13(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_14(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_13(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_15(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_14(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_15(type, field, ...) AURORA_DETAIL_PPC_REVERSE_14(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_15(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_14(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_15(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_14(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_16(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_15(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_16(type, field, ...) AURORA_DETAIL_PPC_REVERSE_15(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_16(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_15(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_16(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_15(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_17(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_16(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_17(type, field, ...) AURORA_DETAIL_PPC_REVERSE_16(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_17(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_16(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_17(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_16(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_18(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_17(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_18(type, field, ...) AURORA_DETAIL_PPC_REVERSE_17(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_18(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_17(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_18(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_17(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_19(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_18(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_19(type, field, ...) AURORA_DETAIL_PPC_REVERSE_18(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_19(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_18(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_19(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_18(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_20(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_19(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_20(type, field, ...) AURORA_DETAIL_PPC_REVERSE_19(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_20(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_19(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_20(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_19(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_21(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_20(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_21(type, field, ...) AURORA_DETAIL_PPC_REVERSE_20(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_21(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_20(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_21(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_20(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_22(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_21(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_22(type, field, ...) AURORA_DETAIL_PPC_REVERSE_21(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_22(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_21(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_22(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_21(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_23(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_22(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_23(type, field, ...) AURORA_DETAIL_PPC_REVERSE_22(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_23(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_22(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_23(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_22(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_24(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_23(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_24(type, field, ...) AURORA_DETAIL_PPC_REVERSE_23(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_24(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_23(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_24(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_23(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_25(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_24(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_25(type, field, ...) AURORA_DETAIL_PPC_REVERSE_24(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_25(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_24(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_25(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_24(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_26(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_25(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_26(type, field, ...) AURORA_DETAIL_PPC_REVERSE_25(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_26(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_25(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_26(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_25(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_27(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_26(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_27(type, field, ...) AURORA_DETAIL_PPC_REVERSE_26(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_27(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_26(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_27(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_26(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_28(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_27(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_28(type, field, ...) AURORA_DETAIL_PPC_REVERSE_27(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_28(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_27(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_28(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_27(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_29(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_28(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_29(type, field, ...) AURORA_DETAIL_PPC_REVERSE_28(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_29(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_28(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_29(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_28(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_30(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_29(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_30(type, field, ...) AURORA_DETAIL_PPC_REVERSE_29(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_30(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_29(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_30(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_29(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_31(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_30(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_31(type, field, ...) AURORA_DETAIL_PPC_REVERSE_30(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_31(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_30(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_31(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_30(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_FORWARD_32(type, field, ...) AURORA_DETAIL_PPC_FIELD(type, field) AURORA_DETAIL_PPC_FORWARD_31(type, __VA_ARGS__)
#define AURORA_DETAIL_PPC_REVERSE_32(type, field, ...) AURORA_DETAIL_PPC_REVERSE_31(type, __VA_ARGS__) AURORA_DETAIL_PPC_FIELD(type, field)
#define AURORA_DETAIL_PPC_SUM_32(field, ...) AURORA_DETAIL_PPC_WIDTH(field) + AURORA_DETAIL_PPC_SUM_31(__VA_ARGS__)
#define AURORA_DETAIL_PPC_VALID_32(type, field, ...) (AURORA_DETAIL_PPC_WIDTH(field) > 0 && AURORA_DETAIL_PPC_WIDTH(field) <= sizeof(type) * 8) && AURORA_DETAIL_PPC_VALID_31(type, __VA_ARGS__)

#if defined(__MWERKS__) || (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#define AURORA_DETAIL_PPC_ORDER AURORA_DETAIL_PPC_FORWARD_
#elif (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) || defined(_WIN32)
#define AURORA_DETAIL_PPC_ORDER AURORA_DETAIL_PPC_REVERSE_
#else
#error "PPC bitfield declarations require a supported host bit allocation order"
#endif

// A typedef checks the full storage width without adding data members, and is
// also accepted by the original C++98 Metrowerks compiler used for Wii proofs.
#define AURORA_PPC_BITFIELD_GROUP(type, ...) \
  typedef char AURORA_DETAIL_PPC_JOIN(aurora_bitfield_width_check_, __LINE__)[ \
      (AURORA_DETAIL_PPC_JOIN(AURORA_DETAIL_PPC_SUM_, AURORA_DETAIL_PPC_COUNT(__VA_ARGS__))(__VA_ARGS__) == \
       sizeof(type) * 8 && AURORA_DETAIL_PPC_JOIN(AURORA_DETAIL_PPC_VALID_, \
      AURORA_DETAIL_PPC_COUNT(__VA_ARGS__))(type, __VA_ARGS__)) ? 1 : -1]; \
  AURORA_DETAIL_PPC_JOIN(AURORA_DETAIL_PPC_ORDER, AURORA_DETAIL_PPC_COUNT(__VA_ARGS__))(type, __VA_ARGS__)
