add_library(aurora_platform STATIC lib/window.cpp)
add_library(aurora::platform ALIAS aurora_platform)
set_target_properties(aurora_platform PROPERTIES FOLDER "aurora")

target_compile_definitions(aurora_platform PUBLIC AURORA TARGET_PC)
target_include_directories(aurora_platform PUBLIC include)
target_link_libraries(aurora_platform PUBLIC aurora::base)
target_link_libraries(aurora_platform PRIVATE absl::btree absl::flat_hash_map sqlite3 TracyClient)

if (AURORA_ENABLE_GX)
    target_compile_definitions(aurora_platform PUBLIC AURORA_ENABLE_GX WEBGPU_DAWN)
    target_sources(aurora_platform PRIVATE
            lib/imgui.cpp
            lib/webgpu/gpu.cpp
            lib/webgpu/gpu_cache.cpp
            lib/webgpu/gpu_prof.cpp
            lib/dawn/BackendBinding.cpp
            lib/dawn/TracyPlatform.cpp
    )
    if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
        set_source_files_properties(lib/dawn/TracyPlatform.cpp PROPERTIES COMPILE_FLAGS -fno-rtti)
    endif ()
    target_link_libraries(aurora_platform PUBLIC imgui)
    target_link_libraries(aurora_platform PRIVATE dawn::webgpu_dawn)
    if (AURORA_CACHE_USE_ZSTD)
        target_compile_definitions(aurora_platform PRIVATE AURORA_CACHE_USE_ZSTD)
        target_link_libraries(aurora_platform PRIVATE zstd::libzstd)
    endif ()
    if (DAWN_ENABLE_VULKAN)
        target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_VULKAN)
    endif ()
    if (DAWN_ENABLE_METAL)
        target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_METAL)
        target_sources(aurora_platform PRIVATE lib/dawn/MetalBinding.mm)
        set_source_files_properties(lib/dawn/MetalBinding.mm PROPERTIES COMPILE_FLAGS -fobjc-arc)
        target_link_options(aurora_platform PUBLIC "LINKER:-weak_framework,Metal")
    endif ()
    if (DAWN_ENABLE_D3D11)
        target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_D3D11)
    endif ()
    if (DAWN_ENABLE_D3D12)
        target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_D3D12)
    endif ()
    if (DAWN_ENABLE_DESKTOP_GL OR DAWN_ENABLE_OPENGLES)
        target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_OPENGL)
        if (DAWN_ENABLE_DESKTOP_GL)
            target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_DESKTOP_GL)
        endif ()
        if (DAWN_ENABLE_OPENGLES)
            target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_OPENGLES)
        endif ()
    endif ()
    if (DAWN_ENABLE_NULL)
        target_compile_definitions(aurora_platform PUBLIC DAWN_ENABLE_BACKEND_NULL)
    endif ()
endif ()
